<#
.SYNOPSIS
  Regenerate assets/THIRD_PARTY_LICENSES.txt from bundled libraries and
  the npm dependency trees of tools/build-marp and tools/build-editor.

.DESCRIPTION
  Run from repo root:
      pwsh -File tools/collect-licenses.ps1

  The script writes assets/THIRD_PARTY_LICENSES.txt deterministically
  (sorted, no timestamps) so successive runs produce a clean diff when
  upstream versions change. Commit the regenerated file.

  Sections:
    1. Directly bundled stand-alone libraries (marked, mermaid, katex,
       highlight.js, smartart). The license body is read from a local
       fallback file under tools/license-texts/ (kept in repo so the
       script has no network dependency).
    2. Transitive npm dependencies of the marp-core IIFE bundle
       (tools/build-marp/node_modules).
    3. Transitive npm dependencies of the CodeMirror editor IIFE bundle
       (tools/build-editor/node_modules).
#>

[CmdletBinding()]
param(
  [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot),
  [string]$OutFile  = $null
)

$ErrorActionPreference = 'Stop'
if (-not $OutFile) { $OutFile = Join-Path $RepoRoot 'assets/THIRD_PARTY_LICENSES.txt' }

$sb = [System.Text.StringBuilder]::new()

function Write-Sep { param([string]$Title)
  [void]$sb.AppendLine('================================================================')
  [void]$sb.AppendLine($Title)
  [void]$sb.AppendLine('================================================================')
}

function Write-Section { param([string]$Title, [string]$Body)
  Write-Sep $Title
  [void]$sb.AppendLine()
  [void]$sb.AppendLine(($Body -replace "`r`n","`n").TrimEnd())
  [void]$sb.AppendLine()
}

# ---- File preamble -------------------------------------------------------
[void]$sb.AppendLine('Third-Party Licenses for md-previewer')
[void]$sb.AppendLine('=====================================')
[void]$sb.AppendLine()
[void]$sb.AppendLine('This file is automatically generated by tools/collect-licenses.ps1.')
[void]$sb.AppendLine('Do not edit by hand. Re-run the script after updating any bundled')
[void]$sb.AppendLine('dependency (marp-core / CodeMirror / etc.) and commit the result.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('The md-previewer Windows binary and its installer redistribute the')
[void]$sb.AppendLine('libraries listed below. Each section names the library, its license,')
[void]$sb.AppendLine('the upstream source, and reproduces the full license text as required')
[void]$sb.AppendLine('by the respective licensing terms.')
[void]$sb.AppendLine()

# ---- Section 1: directly bundled libraries -------------------------------
[void]$sb.AppendLine()
[void]$sb.AppendLine('################################################################')
[void]$sb.AppendLine('# 1. Directly bundled libraries (assets/libs/)')
[void]$sb.AppendLine('################################################################')
[void]$sb.AppendLine()

$direct = @(
  [pscustomobject]@{ Name='marked';        Version='11.1.1'; Spdx='MIT';
    Upstream='https://github.com/markedjs/marked';
    Path='assets/libs/marked.min.js';
    LicenseFile='tools/license-texts/marked.LICENSE' }
  [pscustomobject]@{ Name='highlight.js';  Version='11.9.0'; Spdx='BSD-3-Clause';
    Upstream='https://github.com/highlightjs/highlight.js';
    Path='assets/libs/highlight.js/';
    LicenseFile='tools/license-texts/highlight.js.LICENSE' }
  [pscustomobject]@{ Name='KaTeX';         Version='0.16.x'; Spdx='MIT';
    Upstream='https://github.com/KaTeX/KaTeX';
    Path='assets/libs/katex/';
    LicenseFile='tools/license-texts/katex.LICENSE' }
  [pscustomobject]@{ Name='KaTeX Fonts';   Version='—';      Spdx='OFL-1.1';
    Upstream='https://github.com/KaTeX/KaTeX/tree/main/src/fonts';
    Path='assets/libs/katex/fonts/';
    LicenseFile='tools/license-texts/katex-fonts.LICENSE' }
  [pscustomobject]@{ Name='Mermaid';       Version='(bundled)'; Spdx='MIT';
    Upstream='https://github.com/mermaid-js/mermaid';
    Path='assets/libs/mermaid.min.js';
    LicenseFile='tools/license-texts/mermaid.LICENSE' }
  [pscustomobject]@{ Name='SmartArt (in-house)'; Version='—'; Spdx='Proprietary (md-previewer)';
    Upstream='(this repository)';
    Path='assets/libs/smartart.js';
    LicenseFile='tools/license-texts/smartart.LICENSE' }
  [pscustomobject]@{ Name='Plotly.js (dist-min)'; Version='2.35.2'; Spdx='MIT';
    Upstream='https://github.com/plotly/plotly.js';
    Path='assets/libs/plotly/plotly.min.js';
    LicenseFile='tools/license-texts/plotly.LICENSE' }
  [pscustomobject]@{ Name='js-yaml';      Version='4.1.0'; Spdx='MIT';
    Upstream='https://github.com/nodeca/js-yaml';
    Path='assets/libs/js-yaml.min.js';
    LicenseFile='tools/license-texts/js-yaml.LICENSE' }
)

foreach ($d in $direct) {
  $title = "$($d.Name) $($d.Version)`nSPDX-License-Identifier: $($d.Spdx)`nUpstream: $($d.Upstream)`nBundled at: $($d.Path)"
  $licPath = Join-Path $RepoRoot $d.LicenseFile
  if (Test-Path $licPath) {
    $body = Get-Content -LiteralPath $licPath -Raw
  } else {
    $body = "[WARNING] License text missing — expected at $($d.LicenseFile). Add the upstream LICENSE file there before redistributing."
  }
  Write-Section $title $body
}

# ---- Sections 2 & 3: npm dependency trees --------------------------------
function Add-NpmTree {
  param(
    [string]$BundleName,
    [string]$NodeModulesPath
  )

  if (-not (Test-Path $NodeModulesPath)) {
    Write-Warning "node_modules not found: $NodeModulesPath — run 'npm install' in that directory first."
    return
  }

  [void]$sb.AppendLine()
  [void]$sb.AppendLine('################################################################')
  [void]$sb.AppendLine("# $BundleName — transitive npm dependencies (runtime only)")
  [void]$sb.AppendLine('################################################################')
  [void]$sb.AppendLine()

  # Get the runtime-only package directory list via `npm ls --omit=dev --all
  # --parseable`. This excludes the bundler (esbuild) and its platform-specific
  # @esbuild/* subpackages that npm pulls in via optionalDependencies but which
  # are not part of the runtime IIFE artifact.
  $bundleRoot = Split-Path -Parent $NodeModulesPath
  $runtimePaths = $null
  Push-Location $bundleRoot
  try {
    $raw = & npm ls --omit=dev --all --parseable 2>$null
    if ($LASTEXITCODE -eq 0 -and $raw) {
      # First line is the project root itself; skip it.
      $runtimePaths = @($raw | Where-Object { $_ -and ($_ -ne (Resolve-Path .).Path) })
    }
  } catch {}
  Pop-Location

  if (-not $runtimePaths) {
    Write-Warning "npm ls failed in $bundleRoot — falling back to enumerating all node_modules (includes devDependencies)."
    $pkgDirs = @()
    Get-ChildItem -LiteralPath $NodeModulesPath -Directory | ForEach-Object {
      if ($_.Name -like '@*') {
        Get-ChildItem -LiteralPath $_.FullName -Directory | ForEach-Object { $pkgDirs += $_ }
      } elseif ($_.Name -ne '.bin' -and $_.Name -ne '.package-lock.json') {
        $pkgDirs += $_
      }
    }
  } else {
    $pkgDirs = $runtimePaths | ForEach-Object { Get-Item -LiteralPath $_ -ErrorAction SilentlyContinue } | Where-Object { $_ }
  }

  $entries = foreach ($pd in $pkgDirs) {
    $pjPath = Join-Path $pd.FullName 'package.json'
    if (-not (Test-Path $pjPath)) { continue }
    try { $pj = Get-Content -LiteralPath $pjPath -Raw | ConvertFrom-Json } catch { continue }
    $licFile = Get-ChildItem -LiteralPath $pd.FullName -File `
      | Where-Object { $_.Name -match '^(LICEN[CS]E|COPYING)(\.|-|$)' -or $_.Name -in @('LICENSE','LICENCE','COPYING','LICENSE.md','LICENSE.txt') } `
      | Select-Object -First 1
    [pscustomobject]@{
      Name        = $pj.name
      Version     = $pj.version
      License     = if ($pj.license) { $pj.license } else { '(unspecified)' }
      Repository  = if ($pj.repository -is [string]) { $pj.repository } elseif ($pj.repository) { $pj.repository.url } else { '' }
      LicenseFile = if ($licFile) { $licFile.FullName } else { $null }
    }
  }

  $entries = $entries | Sort-Object Name

  foreach ($e in $entries) {
    $title = "$($e.Name) $($e.Version)`nLicense: $($e.License)"
    if ($e.Repository) { $title += "`nRepository: $($e.Repository)" }
    if ($e.LicenseFile) {
      $body = Get-Content -LiteralPath $e.LicenseFile -Raw
    } else {
      # Fall back to a generic SPDX text shipped under tools/license-texts/.
      $spdxFallback = Join-Path $RepoRoot ("tools/license-texts/{0}.LICENSE" -f $e.License)
      if ($e.License -and (Test-Path $spdxFallback)) {
        $body = "[The npm package shipped no LICENSE file. Reproduced below is the canonical $($e.License) text per the package.json license field.]`n`n"
        $body += Get-Content -LiteralPath $spdxFallback -Raw
      } else {
        $body = "[No LICENSE file shipped in the npm package. License field from package.json: $($e.License)]"
      }
    }
    Write-Section $title $body
  }
}

Add-NpmTree 'Marp Core IIFE bundle (assets/libs/marp/marp.iife.js)' (Join-Path $RepoRoot 'tools/build-marp/node_modules')
Add-NpmTree 'CodeMirror editor IIFE bundle (assets/libs/editor/editor.iife.js)' (Join-Path $RepoRoot 'tools/build-editor/node_modules')

# ---- Write file ----------------------------------------------------------
$dir = Split-Path -Parent $OutFile
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }

# Force LF line endings + UTF-8 (no BOM) for clean cross-platform diffs.
$text = ($sb.ToString() -replace "`r`n","`n")
[System.IO.File]::WriteAllText($OutFile, $text, [System.Text.UTF8Encoding]::new($false))

Write-Host "Wrote $OutFile ($([math]::Round((Get-Item $OutFile).Length / 1024, 1)) KB)"
