"""Generate the tiny 3D sample models used by samples/model3d.md.

Deliberately ASCII / text formats and only a few dozen faces, so the files stay
a few KB and remain diffable in git — the same reasoning behind samples/data's
small CSVs. Re-run after changing the shapes:

    python tools/make-3d-samples/make_3d_samples.py

Shape: an L-shaped prism ("bracket"), profile in XZ extruded along Y. An L is
non-convex, so the caps are emitted as two rectangles rather than a fan.
"""
import pathlib

OUT = pathlib.Path(__file__).resolve().parents[2] / 'samples' / 'data'

# L profile in the XZ plane, counter-clockwise seen from +Y.
#   (0,0) --------------- (60,0)
#     |                     |
#     |                (60,18)
#     |                  |
#   (18,18) ----------- (18,60)?  <- no: build the L explicitly below
W, T, H = 60.0, 18.0, 34.0   # arm length, thickness, height (extrude along Y)

PROFILE = [
    (0.0, 0.0),
    (W, 0.0),
    (W, T),
    (T, T),
    (T, W),
    (0.0, W),
]

# Two rectangles that tile the L exactly (no overlap, no gap).
RECTS = [
    [(0.0, 0.0), (W, 0.0), (W, T), (0.0, T)],
    [(0.0, T), (T, T), (T, W), (0.0, W)],
]


def tri_normal(a, b, c):
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
    n = (nx * nx + ny * ny + nz * nz) ** 0.5 or 1.0
    return (nx / n, ny / n, nz / n)


def build_triangles():
    tris = []
    # Caps. Bottom at y=0 (normal -Y, so wind clockwise), top at y=H (+Y).
    for rect in RECTS:
        p = [(x, 0.0, z) for (x, z) in rect]
        tris.append((p[0], p[2], p[1]))
        tris.append((p[0], p[3], p[2]))
        q = [(x, H, z) for (x, z) in rect]
        tris.append((q[0], q[1], q[2]))
        tris.append((q[0], q[2], q[3]))
    # Sides: one quad per profile edge.
    n = len(PROFILE)
    for i in range(n):
        x0, z0 = PROFILE[i]
        x1, z1 = PROFILE[(i + 1) % n]
        a = (x0, 0.0, z0)
        b = (x1, 0.0, z1)
        c = (x1, H, z1)
        d = (x0, H, z0)
        tris.append((a, b, c))
        tris.append((a, c, d))
    # PROFILE above is wound CLOCKWISE seen from +Y (right-handed X cross Z is
    # -Y), so every triangle emitted from it — caps and sides alike — comes out
    # facing inward. Flip the whole soup once rather than special-casing each
    # loop. Verified by checking the computed normals: bottom cap must be -Y,
    # top +Y, and the z=0 side face -Z.
    return [(a, c, b) for (a, b, c) in tris]


def write_stl(path, tris, name='bracket'):
    lines = ['solid %s' % name]
    for (a, b, c) in tris:
        nx, ny, nz = tri_normal(a, b, c)
        lines.append('  facet normal %.6e %.6e %.6e' % (nx, ny, nz))
        lines.append('    outer loop')
        for v in (a, b, c):
            lines.append('      vertex %.6e %.6e %.6e' % v)
        lines.append('    endloop')
        lines.append('  endfacet')
    lines.append('endsolid %s' % name)
    path.write_text('\n'.join(lines) + '\n', encoding='ascii')
    return len(tris)


def write_obj(path, tris, name='bracket'):
    verts = []
    index = {}
    faces = []
    for tri in tris:
        idx = []
        for v in tri:
            key = tuple(round(c, 6) for c in v)
            if key not in index:
                verts.append(key)
                index[key] = len(verts)
            idx.append(index[key])
        faces.append(idx)
    lines = [
        '# %s - generated by tools/make-3d-samples/make_3d_samples.py' % name,
        'o %s' % name,
    ]
    for v in verts:
        lines.append('v %.6f %.6f %.6f' % v)
    for f in faces:
        lines.append('f %d %d %d' % tuple(f))
    path.write_text('\n'.join(lines) + '\n', encoding='ascii')
    return len(verts), len(faces)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    tris = build_triangles()
    n = write_stl(OUT / 'bracket.stl', tris)
    nv, nf = write_obj(OUT / 'bracket.obj', tris)
    print('bracket.stl: %d facets, %d bytes' % (n, (OUT / 'bracket.stl').stat().st_size))
    print('bracket.obj: %d verts / %d faces, %d bytes' % (nv, nf, (OUT / 'bracket.obj').stat().st_size))


if __name__ == '__main__':
    main()
